const DB_KEY="boshra_quran_system_v1", SESSION_KEY="boshra_current_teacher";
let db; try{db=JSON.parse(localStorage.getItem(DB_KEY))||{}}catch(e){db={}}
["teachers","students","rings","attendance","tracking","tests","complexes"].forEach(k=>{if(!Array.isArray(db[k]))db[k]=[]});
let currentTeacherId=localStorage.getItem(SESSION_KEY)||null;
const $=id=>document.getElementById(id), uid=(p="id")=>p+"_"+Date.now()+"_"+Math.random().toString(36).slice(2,8), today=()=>new Date().toLocaleDateString("en-CA");
function esc(v=""){return String(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
function currentTeacher(){return db.teachers.find(t=>t.id===currentTeacherId)||null} function teacherStudents(){return currentTeacherId?db.students.filter(s=>s.teacherId===currentTeacherId):[]} function teacherRings(){return currentTeacherId?db.rings.filter(r=>r.teacherId===currentTeacherId):[]} function ringName(id){return db.rings.find(r=>r.id===id)?.name||"بدون حلقة"}
function complexName(id){return db.complexes.find(c=>c.id===id)?.name||"بدون مجمع"}
function saveDB(){localStorage.setItem(DB_KEY,JSON.stringify(db));updateStats()}
function updateStats(){if($("studentsCount"))$("studentsCount").textContent=currentTeacherId?teacherStudents().length:db.students.length;if($("ringsCount"))$("ringsCount").textContent=currentTeacherId?teacherRings().length:db.rings.length;if($("teachersCount"))$("teachersCount").textContent=db.teachers.length;if($("todayAttendance")){let ids=new Set((currentTeacherId?teacherStudents():db.students).map(s=>s.id));$("todayAttendance").textContent=db.attendance.filter(a=>a.date===today()&&a.status==="حاضر"&&ids.has(a.studentId)).length}}
function panel(){let p=$("panel");if(!p){p=document.createElement("section");p.id="panel";p.className="panel";(document.querySelector("main")||document.body).appendChild(p)}p.classList.remove("hidden");requestAnimationFrame(()=>p.scrollIntoView({behavior:"smooth",block:"start"}));return p} function closePanel(){let p=$("panel");if(p){p.innerHTML="";p.classList.add("hidden")}} function head(t,s=""){return `<div class="panel-head"><div><h2>${esc(t)}</h2>${s?`<p>${esc(s)}</p>`:""}</div><button onclick="closePanel()">✕</button></div>`}
function openPanel(x){({students:showStudents,complexes:showComplexes,rings:showRings,teachers:showTeachers,attendance:showAttendance,tracking:showTracking,quran:showQuran,tests:showTests,reports:showReports}[x]||(()=>{}))()}
function showTeacher(){let t=currentTeacher();if(!t)return showTeacherLogin();panel().innerHTML=head("حساب المعلم","الملف الشخصي وإدارة الحساب")+`<div class="teacher-profile"><div class="teacher-avatar">👨‍🏫</div><h3>${esc(t.name)}</h3><p>${esc(t.phone||"")}</p><p>الحلقة: <strong>${esc(ringName(t.ringId))}</strong></p><div class="actions"><button onclick="showQuran()">📖 مصحفي</button><button onclick="logoutTeacher()">تسجيل الخروج</button></div></div>`}
function showTeacherLogin(){panel().innerHTML=head("دخول المعلم","اختر حسابك أو أنشئ حسابًا جديدًا")+`<div class="form-card"><label>اختر المعلم</label><select id="loginTeacher"><option value="">اختر المعلم</option>${db.teachers.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join("")}</select><button class="primary" onclick="loginTeacher()">دخول</button><hr><button onclick="showAddTeacher()">+ إنشاء حساب معلم</button></div>`}
function loginTeacher(){let e=$("loginTeacher");if(!e?.value)return alert("اختر المعلم أولًا");currentTeacherId=e.value;localStorage.setItem(SESSION_KEY,currentTeacherId);updateStats();showTeacher()} function logoutTeacher(){currentTeacherId=null;localStorage.removeItem(SESSION_KEY);updateStats();showTeacherLogin()} function enterTeacher(id){currentTeacherId=id;localStorage.setItem(SESSION_KEY,id);updateStats();showTeacher()}
function showTeachers(){panel().innerHTML=head("المعلمون","إدارة حسابات المعلمين")+`<button class="primary" onclick="showAddTeacher()">+ إضافة معلم</button><div class="list">${db.teachers.length?db.teachers.map(t=>`<article class="list-item"><div><h3>👨‍🏫 ${esc(t.name)}</h3><p>${esc(t.phone||"بدون رقم")}</p><small>${esc(ringName(t.ringId))}</small></div><button onclick="enterTeacher('${t.id}')">دخول</button></article>`).join(""):`<p class="empty">لا يوجد معلمون بعد.</p>`}</div>`}
function showAddTeacher(){panel().innerHTML=head("إضافة معلم","إنشاء حساب معلم")+`<div class="form-card"><label>اسم المعلم</label><input id="teacherName"><label>رقم الجوال</label><input id="teacherPhone"><label>الحلقة</label><select id="teacherRing"><option value="">بدون حلقة حاليًا</option>${db.rings.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join("")}</select><button class="primary" onclick="addTeacher()">حفظ المعلم</button></div>`}
function addTeacher(){let n=$("teacherName")?.value.trim();if(!n)return alert("اكتب اسم المعلم");let id=uid("teacher");db.teachers.push({id,name:n,phone:$("teacherPhone")?.value.trim()||"",ringId:$("teacherRing")?.value||"",quran:{lastSurah:"الفاتحة",lastAyah:1,note:""},createdAt:new Date().toISOString()});saveDB();currentTeacherId=id;localStorage.setItem(SESSION_KEY,id);showTeacher()}
function showComplexes(){let cs=db.complexes;panel().innerHTML=head("المجمعات","إدارة المجمعات والحلقات التابعة لها")+`<div class="form-card"><label>اسم المجمع</label><input id="complexName" placeholder="اسم المجمع"><button class="primary" onclick="addComplex()">+ إضافة مجمع</button></div><div class="list">${cs.length?cs.map(c=>`<article class="list-item"><div><h3>🏢 ${esc(c.name)}</h3><small>${db.rings.filter(r=>r.complexId===c.id).length} حلقة</small></div><button onclick="showComplexRings('${c.id}')">فتح الحلقات</button></article>`).join(""):`<p class="empty">لا توجد مجمعات بعد.</p>`}</div>`}
function addComplex(){let n=$("complexName")?.value.trim();if(!n)return alert("اكتب اسم المجمع");db.complexes.push({id:uid("complex"),name:n,createdAt:new Date().toISOString()});saveDB();showComplexes()}
function showComplexRings(complexId){let c=db.complexes.find(x=>x.id===complexId);if(!c)return showComplexes();let rs=db.rings.filter(r=>r.complexId===complexId&&(currentTeacherId?r.teacherId===currentTeacherId:true));panel().innerHTML=head("حلقات "+c.name,"الحلقات التابعة للمجمع")+`<div class="form-card"><label>اسم الحلقة</label><input id="ringName" placeholder="اسم الحلقة"><button class="primary" onclick="addRing('${complexId}')">+ إضافة حلقة</button></div><div class="list">${rs.length?rs.map(r=>`<article class="list-item"><div><h3>🕌 ${esc(r.name)}</h3><small>${db.students.filter(s=>s.ringId===r.id).length} طالب</small></div><button onclick="showRingStudents('${r.id}')">فتح الطلاب</button></article>`).join(""):`<p class="empty">لا توجد حلقات في هذا المجمع.</p>`}</div><div class="actions"><button onclick="showComplexes()">← العودة إلى المجمعات</button></div>`}
function showRingStudents(ringId){let r=db.rings.find(x=>x.id===ringId);if(!r)return;let ss=db.students.filter(s=>s.ringId===ringId&&(currentTeacherId?s.teacherId===currentTeacherId:true));panel().innerHTML=head("طلاب "+r.name,complexName(r.complexId))+`<div class="list">${ss.length?ss.map(s=>`<article class="list-item"><div><h3>👤 ${esc(s.name)}</h3><small>${esc(s.phone||"")}</small></div><button onclick="studentDetails('${s.id}')">متابعة</button></article>`).join(""):`<p class="empty">لا يوجد طلاب في هذه الحلقة.</p>`}</div><div class="actions"><button onclick="showComplexRings('${r.complexId||""}')">← العودة إلى الحلقات</button></div>`}
function showRings(){let rs=currentTeacherId?teacherRings():db.rings;panel().innerHTML=head("الحلقات","إدارة حلقات تحفيظ القرآن")+`<div class="form-card"><label>المجمع</label><select id="ringComplex"><option value="">اختر المجمع</option>${db.complexes.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join("")}</select><label>اسم الحلقة</label><input id="ringName" placeholder="اسم الحلقة"><button class="primary" onclick="addRing()">+ إضافة حلقة</button></div><div class="list">${rs.length?rs.map(r=>`<article class="list-item"><div><h3>🕌 ${esc(r.name)}</h3><p>🏢 ${esc(complexName(r.complexId))}</p><small>${db.students.filter(s=>s.ringId===r.id).length} طالب</small></div><button onclick="showRingStudents('${r.id}')">الطلاب</button></article>`).join(""):`<p class="empty">لا توجد حلقات.</p>`}</div>`}
function addRing(complexId=""){if(!currentTeacherId){alert("سجّل دخول المعلم أولًا");return showTeacherLogin()}let n=$("ringName")?.value.trim();if(!n)return alert("اكتب اسم الحلقة");let cid=complexId||$("ringComplex")?.value||"";if(!cid)return alert("اختر المجمع أولًا");let id=uid("ring");db.rings.push({id,name:n,teacherId:currentTeacherId,complexId:cid});let t=currentTeacher();if(t&&!t.ringId)t.ringId=id;saveDB();complexId?showComplexRings(cid):showRings()}

function showStudents(){if(!currentTeacherId)return showTeacherLogin();let ss=teacherStudents();panel().innerHTML=head("الطلاب","طلاب المعلم الحالي")+`<button class="primary" onclick="showAddStudent()">+ إضافة طالب</button><div class="list">${ss.length?ss.map(s=>`<article class="list-item"><div><h3>👤 ${esc(s.name)}</h3><p>${esc(ringName(s.ringId))}</p><small>${esc(s.phone||"")}</small></div><button onclick="studentDetails('${s.id}')">متابعة</button></article>`).join(""):`<p class="empty">لا يوجد طلاب.</p>`}</div>`}
function showAddStudent(){panel().innerHTML=head("إضافة طالب","إضافة طالب إلى حساب المعلم")+`<div class="form-card"><label>اسم الطالب</label><input id="studentName"><label>رقم ولي الأمر</label><input id="studentPhone"><label>الحلقة</label><select id="studentRing"><option value="">اختر الحلقة</option>${teacherRings().map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join("")}</select><button class="primary" onclick="addStudent()">حفظ الطالب</button></div>`}
function addStudent(){let n=$("studentName")?.value.trim();if(!n)return alert("اكتب اسم الطالب");db.students.push({id:uid("student"),name:n,phone:$("studentPhone")?.value.trim()||"",ringId:$("studentRing")?.value||"",teacherId:currentTeacherId,createdAt:new Date().toISOString()});saveDB();showStudents()}
function studentDetails(id){let s=db.students.find(x=>x.id===id);if(!s)return;let rs=db.tracking.filter(x=>x.studentId===id);panel().innerHTML=head(s.name,ringName(s.ringId))+`<div class="student-summary"><h3>📚 سجل الحفظ</h3>${rs.length?rs.slice().reverse().map(r=>`<article class="record"><strong>${esc(r.surah)}</strong><p>من آية ${esc(r.from)} إلى ${esc(r.to)}</p><small>${esc(r.date)} • ${esc(r.grade)}</small></article>`).join(""):`<p>لا توجد متابعة مسجلة.</p>`}</div>`}
function showAttendance(){if(!currentTeacherId)return showTeacherLogin();let ss=teacherStudents();panel().innerHTML=head("الحضور والغياب","تسجيل حضور اليوم")+`<div class="attendance-list">${ss.map(s=>`<article class="attendance-row"><strong>${esc(s.name)}</strong><select id="att_${s.id}"><option>حاضر</option><option>غائب</option><option>متأخر</option><option>معتذر</option></select></article>`).join("")}</div>${ss.length?`<button class="primary" onclick="saveAttendance()">حفظ الحضور</button>`:`<p>لا يوجد طلاب.</p>`}`}
function saveAttendance(){let d=today();teacherStudents().forEach(s=>{let e=$("att_"+s.id);if(!e)return;db.attendance=db.attendance.filter(a=>!(a.studentId===s.id&&a.date===d));db.attendance.push({id:uid("attendance"),teacherId:currentTeacherId,studentId:s.id,date:d,status:e.value})});saveDB();alert("تم حفظ الحضور");showAttendance()}
function showTracking(){if(!currentTeacherId)return showTeacherLogin();panel().innerHTML=head("الحفظ والمراجعة","تسجيل الورد اليومي")+`<div class="form-card"><label>الطالب</label><select id="trackStudent">${teacherStudents().map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join("")}</select><label>نوع المتابعة</label><select id="trackType"><option>حفظ جديد</option><option>مراجعة</option><option>تلاوة</option></select><label>السورة</label><input id="trackSurah"><label>من آية</label><input id="trackFrom" type="number"><label>إلى آية</label><input id="trackTo" type="number"><label>التقييم</label><select id="trackGrade"><option>ممتاز</option><option>جيد جدًا</option><option>جيد</option><option>يحتاج مراجعة</option></select><label>عدد الأخطاء</label><input id="trackErrors" type="number" value="0"><label>ملاحظات</label><textarea id="trackNotes"></textarea><button class="primary" onclick="saveTracking()">حفظ المتابعة</button></div>`}
function saveTracking(){let sid=$("trackStudent")?.value,s=$("trackSurah")?.value.trim();if(!sid)return alert("أضف طالبًا أولًا");if(!s)return alert("اكتب اسم السورة");db.tracking.push({id:uid("tracking"),teacherId:currentTeacherId,studentId:sid,type:$("trackType").value,surah:s,from:$("trackFrom").value,to:$("trackTo").value,grade:$("trackGrade").value,errors:Number($("trackErrors").value||0),notes:$("trackNotes").value,date:today()});saveDB();alert("تم حفظ متابعة الطالب");showTracking()}
const quranSurahs=["الفاتحة","البقرة","آل عمران","النساء","المائدة","الأنعام","الأعراف","الأنفال","التوبة","يونس","هود","يوسف","الرعد","إبراهيم","الحجر","النحل","الإسراء","الكهف","مريم","طه","الأنبياء","الحج","المؤمنون","النور","الفرقان","الشعراء","النمل","القصص","العنكبوت","الروم","لقمان","السجدة","الأحزاب","سبأ","فاطر","يس","الصافات","ص","الزمر","غافر","فصلت","الشورى","الزخرف","الدخان","الجاثية","الأحقاف","محمد","الفتح","الحجرات","ق","الذاريات","الطور","النجم","القمر","الرحمن","الواقعة","الحديد","المجادلة","الحشر","الممتحنة","الصف","الجمعة","المنافقون","التغابن","الطلاق","التحريم","الملك","القلم","الحاقة","المعارج","نوح","الجن","المزمل","المدثر","القيامة","الإنسان","المرسلات","النبأ","النازعات","عبس","التكوير","الانفطار","المطففين","الانشقاق","البروج","الطارق","الأعلى","الغاشية","الفجر","البلد","الشمس","الليل","الضحى","الشرح","التين","العلق","القدر","البينة","الزلزلة","العاديات","القارعة","التكاثر","العصر","الهمزة","الفيل","قريش","الماعون","الكوثر","الكافرون","النصر","المسد","الإخلاص","الفلق","الناس"];
function showQuran(){let t=currentTeacher();if(!t)return showTeacherLogin();if(!t.quran)t.quran={lastSurah:"الفاتحة",lastAyah:1,note:""};panel().innerHTML=head("📖 مصحف "+t.name,"موضع القراءة الخاص بالمعلم")+`<div class="quran-reader"><div class="quran-cover"><div class="quran-symbol">۞</div><div><h2>القرآن الكريم</h2><p>مصحف المعلم</p><strong>${esc(t.name)}</strong></div></div><div class="form-card"><label>السورة</label><select id="quranSurah">${quranSurahs.map(n=>`<option ${n===t.quran.lastSurah?"selected":""}>${n}</option>`).join("")}</select><label>رقم الآية</label><input id="quranAyah" type="number" min="1" value="${Number(t.quran.lastAyah)||1}"><label>ملاحظات</label><textarea id="quranNote">${esc(t.quran.note||"")}</textarea><button class="primary" onclick="saveQuranPosition()">🔖 حفظ موضع القراءة</button></div></div>`}
function saveQuranPosition(){let t=currentTeacher();if(!t)return;t.quran={lastSurah:$("quranSurah").value,lastAyah:Number($("quranAyah").value||1),note:$("quranNote").value};saveDB();alert("تم حفظ موضع المصحف");showQuran()}
function showTests(){if(!currentTeacherId)return showTeacherLogin();panel().innerHTML=head("الاختبارات والتقييم","تقييم الحفظ والتجويد")+`<div class="form-card"><label>الطالب</label><select id="testStudent">${teacherStudents().map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join("")}</select><label>اسم الاختبار</label><input id="testName"><label>الحفظ / 100</label><input id="memorizationGrade" type="number"><label>التجويد / 100</label><input id="tajweedGrade" type="number"><label>الأخطاء</label><input id="testErrors" type="number" value="0"><label>الملاحظات</label><textarea id="testNotes"></textarea><button class="primary" onclick="saveTest()">حفظ التقييم</button></div>`}
function saveTest(){let sid=$("testStudent")?.value;if(!sid)return alert("اختر الطالب");db.tests.push({id:uid("test"),teacherId:currentTeacherId,studentId:sid,name:$("testName").value,memorization:Number($("memorizationGrade").value||0),tajweed:Number($("tajweedGrade").value||0),errors:Number($("testErrors").value||0),notes:$("testNotes").value,date:today()});saveDB();alert("تم حفظ التقييم");showTests()}
function showReports(){if(!currentTeacherId)return showTeacherLogin();let ss=teacherStudents(),a=db.attendance.filter(x=>x.teacherId===currentTeacherId),r=db.tracking.filter(x=>x.teacherId===currentTeacherId),t=db.tests.filter(x=>x.teacherId===currentTeacherId);panel().innerHTML=head("التقارير","ملخص أداء الحلقة")+`<section class="report-grid"><article><strong>${ss.length}</strong><span>الطلاب</span></article><article><strong>${r.length}</strong><span>سجلات الحفظ</span></article><article><strong>${a.filter(x=>x.status==="حاضر").length}</strong><span>مرات الحضور</span></article><article><strong>${a.filter(x=>x.status==="غائب").length}</strong><span>مرات الغياب</span></article><article><strong>${t.length}</strong><span>الاختبارات</span></article><article><strong>${r.reduce((n,x)=>n+Number(x.errors||0),0)}</strong><span>أخطاء التلاوة</span></article></section>`}
Object.assign(window,{openPanel,closePanel,showTeacher,showTeacherLogin,loginTeacher,logoutTeacher,enterTeacher,showTeachers,showAddTeacher,addTeacher,showComplexes,addComplex,showComplexRings,showRingStudents,showRings,addRing,showStudents,showAddStudent,addStudent,studentDetails,showAttendance,saveAttendance,showTracking,saveTracking,showQuran,saveQuranPosition,showTests,saveTest,showReports});
document.addEventListener("DOMContentLoaded",()=>{if(currentTeacherId&&!db.teachers.some(t=>t.id===currentTeacherId)){currentTeacherId=null;localStorage.removeItem(SESSION_KEY)}updateStats()});

